/*
 * Generic Palette Bitmap Manager for GBA-Studio
 * Handles tile-based map rendering using palette bitmaps
 */

#include "bn_core.h"
#include "bn_math.h"
#include "bn_log.h"
#include "bn_keypad.h"
#include "bn_display.h"
#include "bn_bg_palettes.h"
#include "bn_sprite_text_generator.h"
#include "bn_palette_bitmap_bg_ptr.h"
#include "bn_palette_bitmap_bg_painter.h"
#include "bn_palette_bitmap_pixels_item.h"
#include "bn_palette_bitmap_roi.h"
#include "bn_vector.h"
#include "bn_pair.h"

#include "palette_bitmap_manager.h"
#include "common_info.h"
#include "common_variable_8x16_sprite_font.h"

// Example tileset items (these would be generated by GBA-Studio)
#include "bn_palette_bitmap_items_dungeon_tile_set_16_cores.h"

// namespace
// {
//     void palette_bitmap_manager_demo_scene(bn::sprite_text_generator& text_generator)
//     {
//         constexpr bn::string_view info_text_lines[] = {
//             "Generic Palette Bitmap Manager Demo",
//             "",
//             "A: Update random tile",
//             "B: Fill area",
//             "START: go to next scene",
//         };

//         common::info info("Palette Manager Demo", info_text_lines, text_generator);

//         // Create sample tile map (10x8 tiles)
//         bn::vector<bn::vector<int>, 64> sample_map;
//         for(int y = 0; y < 8; ++y)
//         {
//             bn::vector<int, 64> row;
//             for(int x = 0; x < 10; ++x)
//             {
//                 // Create a simple pattern
//                 int tile_index = (x + y) % 4; // Cycle through first 4 tiles
//                 row.push_back(tile_index);
//             }
//             sample_map.push_back(row);
//         }

//         // Initialize the generic palette bitmap manager
//         PaletteBitmapManager palette_manager;
//         palette_manager.initialize(
//             bn::palette_bitmap_items::dungeon_tile_set_16_cores.pixels_item(),
//             sample_map,
//             16, // tile_width
//             16, // tile_height
//             10, // map_width
//             8,  // map_height
//             40, // offset_x
//             40  // offset_y
//         );

//         // Render initial map
//         palette_manager.render_map();

//         while(! bn::keypad::start_pressed())
//         {
//             info.update();

//             // Demo: Update random tile when A is pressed
//             if(bn::keypad::a_pressed())
//             {
//                 int random_x = bn::random() % 10;
//                 int random_y = bn::random() % 8;
//                 int random_tile = bn::random() % 16; // Assuming 16 different tiles available

//                 palette_manager.update_tile(random_x, random_y, random_tile);
//                 BN_LOG("Updated tile at (", random_x, ",", random_y, ") to ", random_tile);
//             }

//             // Demo: Fill area when B is pressed
//             if(bn::keypad::b_pressed())
//             {
//                 int fill_tile = 5; // Use tile index 5 for filling
//                 palette_manager.fill_area(2, 2, 3, 3, fill_tile);
//                 BN_LOG("Filled area 3x3 at (2,2) with tile ", fill_tile);
//             }

//             bn::core::update();
//         }
//     }
// }

// // ----------------- Implementação da classe -----------------

// PaletteBitmapManager::PaletteBitmapManager()
//     : tile_width(16), tile_height(16), map_width(20), map_height(15),
//       offset_x(0), offset_y(0)
// {
// }

// PaletteBitmapManager::~PaletteBitmapManager()
// {
//     bg.reset();
//     painter.reset();
//     pixels_item.reset();
// }

// void PaletteBitmapManager::initialize(
//     const bn::palette_bitmap_pixels_item& tileset_item,
//     const bn::vector<bn::vector<int, 64>, 64>& map_data,
//     int tile_w,
//     int tile_h,
//     int map_w,
//     int map_h,
//     int offset_x_pos,
//     int offset_y_pos
// )
// {
//     // Store parameters
//     pixels_item = tileset_item;
//     tile_map = map_data;
//     tile_width = tile_w;
//     tile_height = tile_h;
//     map_width = map_w;
//     map_height = map_h;
//     offset_x = offset_x_pos;
//     offset_y = offset_y_pos;

//     // Validate map data dimensions
//     if (tile_map.size() != static_cast<size_t>(map_height)) {
//         BN_LOG("Warning: Map height mismatch. Expected: ", map_height, ", Got: ", tile_map.size());
//     }

//     for (size_t i = 0; i < tile_map.size(); ++i) {
//         if (tile_map[i].size() != static_cast<size_t>(map_width)) {
//             BN_LOG("Warning: Map width mismatch at row ", i, ". Expected: ", map_width, ", Got: ", tile_map[i].size());
//         }
//     }

//     // Create background
//     bg = bn::palette_bitmap_bg_ptr::create(tileset_item.palette_item());
//     painter = bn::palette_bitmap_bg_painter(bg.value());

//     BN_LOG("PaletteBitmapManager initialized with map size: ", map_width, "x", map_height,
//            " tiles (", tile_width, "x", tile_height, "px each)");
// }

// void PaletteBitmapManager::render_map()
// {
//     if (!is_initialized()) {
//         BN_LOG("PaletteBitmapManager not initialized");
//         return;
//     }

//     painter->clear();

//     // Calculate tiles per row in the tileset
//     int tileset_width = pixels_item->width();
//     int tiles_per_row = tileset_width / tile_width;

//     // Render each tile in the map
//     for (int y = 0; y < map_height; ++y) {
//         for (int x = 0; x < map_width; ++x) {
//             int tile_index = get_tile(x, y);
//             if (tile_index >= 0) {
//                 // Calculate screen position
//                 int screen_x = offset_x + (x * tile_width);
//                 int screen_y = offset_y + (y * tile_height);

//                 // Calculate tileset position
//                 auto [tileset_x, tileset_y] = get_tileset_position(tile_index, tiles_per_row);

//                 // Create ROI for this tile
//                 bn::palette_bitmap_roi tile_roi(
//                     pixels_item.value(),
//                     tileset_x, tileset_y,
//                     tile_width, tile_height
//                 );

//                 // Render tile
//                 painter->blit(screen_x, screen_y, tile_roi);
//             }
//         }
//     }

//     painter->flip_page_later();
// }

// void PaletteBitmapManager::update_tile(int x, int y, int tile_index)
// {
//     if (!is_initialized() || x < 0 || x >= map_width || y < 0 || y >= map_height) {
//         return;
//     }

//     // Update tile map
//     if (static_cast<size_t>(y) < tile_map.size() &&
//         static_cast<size_t>(x) < tile_map[y].size()) {
//         tile_map[y][x] = tile_index;
//     }

//     // Re-render the specific tile
//     render_single_tile(x, y, tile_index);
// }

// void PaletteBitmapManager::fill_area(int start_x, int start_y, int width, int height, int tile_index)
// {
//     if (!is_initialized()) {
//         return;
//     }

//     int end_x = bn::min(start_x + width, map_width);
//     int end_y = bn::min(start_y + height, map_height);

//     for (int y = bn::max(0, start_y); y < end_y; ++y) {
//         for (int x = bn::max(0, start_x); x < end_x; ++x) {
//             if (static_cast<size_t>(y) < tile_map.size() &&
//                 static_cast<size_t>(x) < tile_map[y].size()) {
//                 tile_map[y][x] = tile_index;
//             }
//         }
//     }

//     // Re-render the entire map (could be optimized to render only the affected area)
//     render_map();
// }

// void PaletteBitmapManager::clear_map(int tile_index)
// {
//     if (!is_initialized()) {
//         return;
//     }

//     for (auto& row : tile_map) {
//         for (auto& tile : row) {
//             tile = tile_index;
//         }
//     }

//     render_map();
// }

// int PaletteBitmapManager::get_tile(int x, int y) const
// {
//     if (x < 0 || x >= map_width || y < 0 || y >= map_height) {
//         return -1;
//     }

//     if (static_cast<size_t>(y) < tile_map.size() &&
//         static_cast<size_t>(x) < tile_map[y].size()) {
//         return tile_map[y][x];
//     }

//     return -1;
// }

// bool PaletteBitmapManager::is_initialized() const
// {
//     return bg.has_value() && painter.has_value() && pixels_item.has_value();
// }

// bn::pair<int, int> PaletteBitmapManager::get_tileset_position(int tile_index, int tiles_per_row) const
// {
//     int tileset_x = (tile_index % tiles_per_row) * tile_width;
//     int tileset_y = (tile_index / tiles_per_row) * tile_height;
//     return bn::pair<int, int>(tileset_x, tileset_y);
// }

// void PaletteBitmapManager::render_single_tile(int screen_x, int screen_y, int tile_index)
// {
//     if (!is_initialized() || tile_index < 0) {
//         return;
//     }

//     // Calculate tiles per row in the tileset
//     int tileset_width = pixels_item->width();
//     int tiles_per_row = tileset_width / tile_width;

//     // Calculate screen position
//     int actual_screen_x = offset_x + (screen_x * tile_width);
//     int actual_screen_y = offset_y + (screen_y * tile_height);

//     // Calculate tileset position
//     auto [tileset_x, tileset_y] = get_tileset_position(tile_index, tiles_per_row);

//     // Create ROI for this tile
//     bn::palette_bitmap_roi tile_roi(
//         pixels_item.value(),
//         tileset_x, tileset_y,
//         tile_width, tile_height
//     );

//     // Render tile
//     painter->blit(actual_screen_x, actual_screen_y, tile_roi);
//     painter->flip_page_later();
// }