/**
 * GBA-Studio Generated Tilemap Integration Example
 *
 * This file shows how GBA-Studio would generate code to integrate
 * tilemaps and tilesets with the generic PaletteBitmapManager.
 */

#include "bn_core.h"
#include "bn_log.h"
#include "bn_string.h"
#include "bn_vector.h"
#include "bn_palette_bitmap_items.h" // Generated by GBA-Studio

#include "palette_bitmap_manager.h"
#include "graphics_manager.h"

// Example of generated tileset items (would be created by GBA-Studio)
// #include "bn_palette_bitmap_items_my_tileset.h"

// Example of generated tilemap data (would be created by GBA-Studio)
/*
const int MY_TILEMAP_DATA[] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 0,
    2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
    // ... more tile data
};
const int MY_TILEMAP_DATA_SIZE = sizeof(MY_TILEMAP_DATA) / sizeof(int);
*/

// Example function showing how GBA-Studio would generate tileset getter
bn::optional<bn::palette_bitmap_pixels_item> get_tileset_item_from_name(const bn::string<64>& name)
{
    // This function would be auto-generated by GBA-Studio based on project tilesets
    if(name == bn::string<64>("dungeon_tile_set_16_cores"))
        return bn::palette_bitmap_items::dungeon_tile_set_16_cores.pixels_item();

    // Add more tilesets as generated by GBA-Studio
    // if(name == bn::string<64>("my_custom_tileset"))
    //     return bn::palette_bitmap_items::my_custom_tileset.pixels_item();

    return bn::nullopt;
}

// Example function showing how GBA-Studio would generate tilemap resource getter
const Resource* get_tilemap_resource_from_name(const bn::string<64>& name)
{
    // This function would be auto-generated by GBA-Studio based on project tilemaps
    // For now, return nullptr as placeholder
    BN_LOG("Tilemap resource lookup not implemented for: ", name.data());
    return nullptr;
}

// Example of how to use the PaletteBitmapManager in a scene
void example_scene_with_tilemap()
{
    // Initialize GraphicsManager (includes tilemap initialization)
    GraphicsManager graphics_mgr;
    graphics_mgr.initialize();

    // Initialize tilemap for current scene
    graphics_mgr.initialize_tilemap();

    // Main game loop
    while(true)
    {
        // Render tilemap
        graphics_mgr.render_tilemap();

        // Example: Update a tile dynamically
        // graphics_mgr.update_tile(5, 5, 10);

        // Example: Fill an area
        // graphics_mgr.fill_tile_area(0, 0, 3, 3, 15);

        // Update other graphics
        graphics_mgr.update_sprites();

        bn::core::update();
    }
}

// Example of direct PaletteBitmapManager usage (alternative approach)
void example_direct_palette_manager_usage()
{
    // Create tile map data (this would come from GBA-Studio generated data)
    bn::vector<bn::vector<int>, 64> tile_map;
    // Initialize with your tile data...

    // Create and initialize palette manager
    PaletteBitmapManager palette_mgr;
    palette_mgr.initialize(
        bn::palette_bitmap_items::dungeon_tile_set_16_cores.pixels_item(),
        tile_map,
        16, 16,  // tile dimensions
        20, 15,  // map dimensions
        0, 0     // offset
    );

    // Use in game loop
    while(true)
    {
        palette_mgr.render_map();

        // Interactive tile editing
        if(bn::keypad::a_pressed())
        {
            palette_mgr.update_tile(10, 8, 5);
        }

        bn::core::update();
    }
}